# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wZOL7fOkNJULUZJ1rUkUKxGi3jkkli3G
"""

# Import necessary libraries
import pandas as pd
from google.colab import files

# Prompt user to upload a file
print("Iltimos, CSV faylingizni yuklang:")
uploaded = files.upload()

# Read the uploaded file (assuming a single file is uploaded)
for filename in uploaded.keys():
    data = pd.read_csv(filename)

# Filter data for Afghanistan
afghanistan_data = data[data['Country'] == 'Afghanistan']

# Count the number of unique dates where programs or reports exist (assuming each date corresponds to a program entry)
unique_dates = afghanistan_data['Date_reported'].nunique()

# Display the result
print(f"Afghanistan uchun jami {unique_dates} ta COVID dasturi yoki hisobot kuni mavjud.")